<?php

	return array(
		'' => 'Please Select One',
		'--U S A--' => array(
			'AL' => 'Alabama',
			'AK' => 'Alaska',
			'AZ' => 'Arizona',
			'AR' => 'Arkansas',
			'CA' => 'California',
			'CO' => 'Colorado',
			'CT' => 'Connecticut',
			'DE' => 'Delaware',
			'DC' => 'District of Columbia',
			'FL' => 'Florida',
			'GA' => 'Georgia',
			'HI' => 'Hawaii',
			'ID' => 'Idaho',
			'IL' => 'Illinois',
			'IN' => 'Indiana',
			'IA' => 'Iowa',
			'KS' => 'Kansas',
			'KY' => 'Kentucky',
			'LA' => 'Louisiana',
			'ME' => 'Maine',
			'MD' => 'Maryland',
			'MA' => 'Massachusetts',
			'MI' => 'Michigan',
			'MN' => 'Minnesota',
			'MS' => 'Mississippi',
			'MO' => 'Missouri',
			'MT' => 'Montana',
			'NE' => 'Nebraska',
			'NV' => 'Nevada',
			'NH' => 'New Hampshire',
			'NJ' => 'New Jersey',
			'NM' => 'New Mexico',
			'NY' => 'New York',
			'NC' => 'North Carolina',
			'ND' => 'North Dakota',
			'OH' => 'Ohio',
			'OK' => 'Oklahoma',
			'OR' => 'Oregon',
			'PA' => 'Pennsylvania',
			'RI' => 'Rhode Island',
			'SC' => 'South Carolina',
			'SD0' => 'South Dakota',
			'TN0' => 'Tennessee',
			'TX0' => 'Texas',
			'UT0' => 'Utah',
			'VT0' => 'Vermont',
			'VA0' => 'Virginia',
			'WA0' => 'Washington',
			'WV0' => 'West Virginia',
			'WI0' => 'Wisconsin',
			'WY0' => 'Wyoming',
		),
		'Canada' => array(
			'AB1' => 'Alberta',
			'BC1' => 'British Columbia',
			'MB1' => 'Manitoba',
			'NB1' => 'New Brunswick',
			'NF1' => 'Newfoundland',
			'NT1' => 'Northwest Territories',
			'NS1' => 'Nova Scotia',
			'NU1' => 'Nunavut',
			'ON1' => 'Ontario',
			'PE1' => 'Prince Edward Island',
			'PQ1' => 'Quebec',
			'SK1' => 'Saskatchewan',
			'YT1' => 'Yukon Territory',
		),
		'Australia' => array(
			'AC2' => 'Australian Capital Territory',
			'NS2' => 'New South Wales',
			'NT2' => 'Northern Territory',
			'QL2' => 'Queensland',
			'SA2' => 'South Australia',
			'TA2' => 'Tasmania',
			'VI2' => 'Victoria',
			'WA2' => 'Western Australia',
		),
	);

?>